// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwtdollzzxqkqqbyussq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3dGRvbGx6enhxa3FxYnl1c3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODc5NjYsImV4cCI6MjA1Njg2Mzk2Nn0.zZC1NCXoCrrmkQaBLM3yP-YoAmIo-gn5xzgbsqeJ-VM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);